Groupware.WAS/Controllers/Common/LoginController.cs
using DAO;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace Groupware.Base.Controllers.common
{
    public class LoginController : Controller
    {
        //
        // GET: /Login/

        public ActionResult Index( )
        {

            return View("~/views/common/Login/Login.cshtml");
        }

		[HttpPost]
		public JObject LoginProcess()
		{
			JObject jsonObj = new JObject();
			string strId = Request.Form["id"];

			DaoAccount daoAcount = new DaoAccount();

			CAccount emp = daoAcount.getAcount(Request.Form["id"], Request.Form["passwd"]);
			if (emp == null)
			{
				jsonObj.Add("RESULT", "FAIL");
				jsonObj.Add("MSG", "해당되는 사용자가 없습니다.");
			}
			else
			{
				LoginProcess(emp);
				jsonObj.Add("RESULT", "OK");
			}

			return jsonObj;
		}

		public void LoginProcess( CAccount emp )
		{
			Session["idx"] = emp.idx;
			Session["emp_no"] = emp.emp_no;
			Session["name"] = emp.name;
			Session["id"] = emp.id;
			Session["email"] = emp.email;
			Session["reg_date"] = emp.reg_date;
			Session["mod_date"] = emp.mod_date;
			Session["is_used"] = emp.is_used;
			Session["is_admin"] = emp.is_admin;
			Session.Timeout = 240;
		}

		public ActionResult Logout()
		{
			Session.Clear();
			return Index();
		}

		public ActionResult LoginCheck()
		{
			return null;
		}
    }
}

Groupware.WAS/Controllers/Layout/HeaderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Groupware.Base.Controllers.Layout
{
    public class HeaderController : Controller
    {
        //
        // GET: /Header/

        public ActionResult Index()
        {
					ViewBag.HeaderTitle = "Groupware Base";

					return PartialView("~/views/layout/Header.cshtml");
        }

    }
}

Groupware.WAS/Controllers/Layout/LeftController.cs
using DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Groupware.Base.Controllers.Layout
{
    public class LeftController : Controller
    {
        //
        // GET: /Left/

        public ActionResult Index()
        {
			IList<CCode> listTree = new List<CCode>();
			try
			{
				DaoCode daoTree = new DaoCode();
				listTree = daoTree.getCodeList("leftmenu", 0, null, 2);
				ViewBag.listTree = listTree;
			}
			catch (Exception e)
			{
				throw new Exception(e.Message);
			}

			return PartialView("~/views/layout/LeftMenu.cshtml", listTree);
        }

    }
}

Groupware.WAS/Views/Shared/Blank.cshtml
@{
	ViewBag.Title = "Blank";
}


<div class="row">
	<div class="col-lg-12">

		<!-- /.panel -->
		<div class="panel panel-default">
			<div class="panel-heading">
				@ViewBag.PanelTitle
			</div>
			<!-- /.panel-heading -->
			<div class="panel-body">


			</div>
			<!-- /.panel-body -->
		</div>
		<!-- /.panel -->

	</div>
	<!-- /.col-lg-12 -->
</div>
<!-- /.row -->

Groupware.WAS/Views/Shared/_Layout.cshtml
@{
	var bootstrap_themes = "ace-v1.2--bs-v3.2.0";
}

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<meta charset="utf-8" />
    <title>@ViewBag.Title</title>
	<meta name="description" content="Restyling jQuery UI Widgets and Elements" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />

	<!--jquery-->
	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/modernizr")
	@Scripts.Render("~/bundles/jquery")


	<!-- jquery library -->
	@Scripts.Render("~/jquerylib/jstree-js")
	@Styles.Render("~/jquerylib/jstree-css")



	<!-- START : Bootstrap Templete -->
		<!-- basic styles -->

		<link rel="stylesheet" href="~/Bootstrap/@bootstrap_themes/assets/css/bootstrap.min.css" />
		<link rel="stylesheet" href="~/Bootstrap/@bootstrap_themes/assets/css/font-awesome.min.css" />

		<!--[if IE 7]>
		  <link rel="stylesheet" href="~/Bootstrap/@bootstrap_themes/assets/css/font-awesome-ie7.min.css" />
		<![endif]-->

		<!-- page specific plugin styles -->
		<link rel="stylesheet" href="~/Bootstrap/@bootstrap_themes/assets/css/jquery-ui.min.css" />

		<!-- fonts -->
		<link rel="stylesheet" href="~/Bootstrap/@bootstrap_themes/assets/css/ace-fonts.css" />

		<!-- ace styles -->

		<link rel="stylesheet" href="~/Bootstrap/@bootstrap_themes/assets/css/ace.min.css" />
		<link rel="stylesheet" href="~/Bootstrap/@bootstrap_themes/assets/css/ace-rtl.min.css" />
		<link rel="stylesheet" href="~/Bootstrap/@bootstrap_themes/assets/css/ace-skins.min.css" />

		<!--[if lte IE 8]>
		  <link rel="stylesheet" href="~/Bootstrap/@bootstrap_themes/assets/css/ace-ie.min.css" />
		<![endif]-->

		<!-- inline styles related to this page -->

		<!-- ace settings handler -->

		<script src="~/Bootstrap/@bootstrap_themes/assets/js/ace-extra.min.js"></script>

		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->

		<!--[if lt IE 9]>
		<script src="~/Bootstrap/@bootstrap_themes/assets/js/html5shiv.js"></script>
		<script src="~/Bootstrap/@bootstrap_themes/assets/js/respond.min.js"></script>
		<![endif]-->
	<!-- END : Bootstrap Templete -->

	<!-- Groupware JS -->
	@Scripts.Render("~/custom/common-js")


</head>
<body>

	<div id="wrapper">

		@RenderBody()
	
		@RenderSection("scripts", required: false)

	</div>
	<!-- /#wrapper -->




	<!-- basic scripts -->

	<!--[if !IE]> -->
	<script type="text/javascript">
		window.jQuery || document.write("<script src='~/Bootstrap/@bootstrap_themes/assets/js/jquery.min.js'>" + "<" + "/script>");
	</script>

	<!-- <![endif]-->

	<!--[if IE]>
	<script type="text/javascript">
		window.jQuery || document.write("<script src='~/Bootstrap/@bootstrap_themes/assets/js/jquery1x.min.js'>"+"<"+"/script>");
	</script>
	<![endif]-->
	<script type="text/javascript">
		if ('ontouchstart' in document.documentElement) document.write("<script src='~/Bootstrap/@bootstrap_themes/assets/js/jquery.mobile.custom.min.js'>" + "<" + "/script>");
	</script>
	<script src="~/Bootstrap/@bootstrap_themes/assets/js/bootstrap.min.js"></script>

	<!-- page specific plugin scripts -->
	<script src="~/Bootstrap/@bootstrap_themes/assets/js/jquery-ui.min.js"></script>
	<script src="~/Bootstrap/@bootstrap_themes/assets/js/jquery.ui.touch-punch.min.js"></script>

	<!-- ace scripts -->
	<script src="~/Bootstrap/@bootstrap_themes/assets/js/ace-elements.min.js"></script>
	<script src="~/Bootstrap/@bootstrap_themes/assets/js/ace.min.js"></script>

	@RenderPage("~/Views/Common/Dialog/AlertDialog.cshtml")
	@RenderPage("~/Views/Common/Dialog/EmpDialog.cshtml")

</body>

</html>

Groupware.WAS/Views/Shared/_MainLayout.cshtml
@{
	var bootstrap_themes = "ace-v1.2--bs-v3.2.0";
	
	if ( Session["emp_no"] == null || Session["emp_no"] == "" )
	{
		//Html.RenderAction("Index", "Login");
	}
}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<meta charset="utf-8" />
    <title>@ViewBag.Title</title>
	<meta name="description" content="Restyling jQuery UI Widgets and Elements" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />

	<!--jquery-->
	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/modernizr")
	@Scripts.Render("~/bundles/jquery")


	<!-- jquery library -->
	@Scripts.Render("~/jquerylib/jstree-js")
	@Styles.Render("~/jquerylib/jstree-css")



	<!-- START : Bootstrap Templete -->
		<!-- basic styles -->

		<link rel="stylesheet" href="~/Bootstrap/@bootstrap_themes/assets/css/bootstrap.min.css" />
		<link rel="stylesheet" href="~/Bootstrap/@bootstrap_themes/assets/css/font-awesome.min.css" />

		<!--[if IE 7]>
		  <link rel="stylesheet" href="~/Bootstrap/@bootstrap_themes/assets/css/font-awesome-ie7.min.css" />
		<![endif]-->

		<!-- page specific plugin styles -->
		<link rel="stylesheet" href="~/Bootstrap/@bootstrap_themes/assets/css/jquery-ui.min.css" />

		<!-- fonts -->
		<link rel="stylesheet" href="~/Bootstrap/@bootstrap_themes/assets/css/ace-fonts.css" />

		<!-- ace styles -->

		<link rel="stylesheet" href="~/Bootstrap/@bootstrap_themes/assets/css/ace.min.css" />
		<link rel="stylesheet" href="~/Bootstrap/@bootstrap_themes/assets/css/ace-rtl.min.css" />
		<link rel="stylesheet" href="~/Bootstrap/@bootstrap_themes/assets/css/ace-skins.min.css" />

		<!--[if lte IE 8]>
		  <link rel="stylesheet" href="~/Bootstrap/@bootstrap_themes/assets/css/ace-ie.min.css" />
		<![endif]-->

		<!-- inline styles related to this page -->

		<!-- ace settings handler -->

		<script src="~/Bootstrap/@bootstrap_themes/assets/js/ace-extra.min.js"></script>

		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->

		<!--[if lt IE 9]>
		<script src="~/Bootstrap/@bootstrap_themes/assets/js/html5shiv.js"></script>
		<script src="~/Bootstrap/@bootstrap_themes/assets/js/respond.min.js"></script>
		<![endif]-->
	<!-- END : Bootstrap Templete -->

	<!-- Groupware JS -->
	@Scripts.Render("~/custom/common-js")


</head>
<body class="no-skin">

	<div class="navbar navbar-default" id="navbar">
		@{
			Html.RenderAction("Index", "Header"); 
		}
	</div>

	<div class="main-container" id="main-container">
		<script type="text/javascript">
			try { ace.settings.check('main-container', 'fixed') } catch (e) { }
		</script>

		<div class="main-container-inner">
			<a class="menu-toggler" id="menu-toggler" href="#">
				<span class="menu-text"></span>
			</a>

			<div class="sidebar responsive" id="sidebar">
				@{
					Html.RenderAction("Index", "Left");
				}
			</div>

			<div class="main-content">
				<div class="breadcrumbs" id="breadcrumbs">
					<script type="text/javascript">
						try { ace.settings.check('breadcrumbs', 'fixed') } catch (e) { }
					</script>

					<ul class="breadcrumb">
						<li>
							<i class="icon-home home-icon"></i>
							<a href="#">Home</a>
						</li>

@*						<li>
							<a href="#">Other Pages</a>
						</li>*@
						<li class="active">@ViewBag.TItle</li>
					</ul><!-- .breadcrumb -->

					<div class="nav-search" id="nav-search">
						<form class="form-search">
							<span class="input-icon">
								<input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
								<i class="icon-search nav-search-icon"></i>
							</span>
						</form>
					</div><!-- #nav-search -->
				</div>

				<div class="page-content">
					<div class="page-header">
						<h1>
							@ViewBag.Title
							@if (ViewBag.Desc != null)
							{
							<small>
								<i class="icon-double-angle-right"></i>
								@ViewBag.Desc
							</small>		   
							}
						</h1>
					</div>
					<div class="row">
						<div class="col-xs-12">
							<!-- PAGE CONTENT BEGINS -->

							@RenderBody()

							<!-- PAGE CONTENT ENDS -->
						</div><!-- /.col -->
					</div><!-- /.row -->
				</div><!-- /.page-content -->
			</div><!-- /.main-content -->

				

			<!-- 환경설정 -->
			<div class="ace-settings-container" id="ace-settings-container">
				<div class="btn btn-app btn-xs btn-warning ace-settings-btn" id="ace-settings-btn">
					<i class="icon-cog bigger-150"></i>
				</div>

				<div class="ace-settings-box" id="ace-settings-box">
					<div>
						<div class="pull-left">
							<select id="skin-colorpicker" class="hide">
								<option data-skin="default" value="#438EB9">#438EB9</option>
								<option data-skin="skin-1" value="#222A2D">#222A2D</option>
								<option data-skin="skin-2" value="#C6487E">#C6487E</option>
								<option data-skin="skin-3" value="#D0D0D0">#D0D0D0</option>
							</select>
						</div>
						<span>&nbsp; Choose Skin</span>
					</div>

					<div>
						<input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-navbar" />
						<label class="lbl" for="ace-settings-navbar"> Fixed Navbar</label>
					</div>

					<div>
						<input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-sidebar" />
						<label class="lbl" for="ace-settings-sidebar"> Fixed Sidebar</label>
					</div>

					<div>
						<input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-breadcrumbs" />
						<label class="lbl" for="ace-settings-breadcrumbs"> Fixed Breadcrumbs</label>
					</div>

					<div>
						<input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-rtl" />
						<label class="lbl" for="ace-settings-rtl"> Right To Left (rtl)</label>
					</div>

					<div>
						<input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-add-container" />
						<label class="lbl" for="ace-settings-add-container">
							Inside
							<b>.container</b>
						</label>
					</div>
				</div>
			</div><!-- /#ace-settings-container -->

		</div>

	</div>

	
	@RenderSection("scripts", required: false)


	<!-- basic scripts -->

	<!--[if !IE]> -->
	<script type="text/javascript">
		window.jQuery || document.write("<script src='~/Bootstrap/@bootstrap_themes/assets/js/jquery.min.js'>" + "<" + "/script>");
	</script>

	<!-- <![endif]-->

	<!--[if IE]>
	<script type="text/javascript">
		window.jQuery || document.write("<script src='~/Bootstrap/@bootstrap_themes/assets/js/jquery1x.min.js'>"+"<"+"/script>");
	</script>
	<![endif]-->
	<script type="text/javascript">
		if ('ontouchstart' in document.documentElement) document.write("<script src='~/Bootstrap/@bootstrap_themes/assets/js/jquery.mobile.custom.min.js'>" + "<" + "/script>");
	</script>
	<script src="~/Bootstrap/@bootstrap_themes/assets/js/bootstrap.min.js"></script>

	<!-- page specific plugin scripts -->
	<script src="~/Bootstrap/@bootstrap_themes/assets/js/jquery-ui.min.js"></script>
	<script src="~/Bootstrap/@bootstrap_themes/assets/js/jquery.ui.touch-punch.min.js"></script>

	<!-- ace scripts -->
	<script src="~/Bootstrap/@bootstrap_themes/assets/js/ace-elements.min.js"></script>
	<script src="~/Bootstrap/@bootstrap_themes/assets/js/ace.min.js"></script>

	@RenderPage("~/Views/Common/Dialog/AlertDialog.cshtml")
	@RenderPage("~/Views/Common/Dialog/EmpDialog.cshtml")

</body>

</html>