Groupware.WAS/Controllers/Command/CommandController.cs
using DAO;
using Groupware.Base.Controllers.Utilities;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Utilities;

namespace Groupware.Base.Controllers.Command
{
    public class CommandController : Controller
    {
        //
        // GET: /Command/

        public ActionResult Index()
        {
            return View("~/Views/Command/Index.cshtml");
        }

		public ActionResult List()
		{
			DaoCommand daoCommand = new DaoCommand();
			IList<CCommand> listCommand = new List<CCommand>();

			if (Session["emp_no"] == null)
			{
				RedirectToAction("Index", "Login");
			}

			try
			{
				int totalCount = 0;
				int pageNum = (Request["pageNum"] == null) ? 1 : int.Parse(Request["pageNum"]);
				int limitCount = (Session["limitCount"] != null) ? int.Parse(Session["limitCount"].ToString()) : 20;

				TagBuilder tag = new TagBuilder("pageinfo");

				if (Request["list_type"] == "send")
				{
					totalCount = daoCommand.getCommandCount(Request["search_key"], Request["search_value"], Session["emp_no"].ToString(), null);
					listCommand = daoCommand.getCommandList(Request["search_key"], Request["search_value"], Session["emp_no"].ToString(), null, pageNum, limitCount);
				}
				else if (Request["list_type"] == "receive")
				{
					totalCount = daoCommand.getCommandCount(Request["search_key"], Request["search_value"], null, Session["emp_no"].ToString());
					listCommand = daoCommand.getCommandList(Request["search_key"], Request["search_value"], null, Session["emp_no"].ToString(), pageNum, limitCount);
				}
				else
				{
					totalCount = daoCommand.getCommandCount(Request["search_key"], Request["search_value"], null, null);
					listCommand = daoCommand.getCommandList(Request["search_key"], Request["search_value"], null, null, pageNum, limitCount);
				}
				PageInfo pageInfo = new PageInfo();
				pageInfo.TotalItems = totalCount;
				pageInfo.CurrentPage = pageNum;
				pageInfo.ItemsPerPage = limitCount;

				ViewBag.listCommand = listCommand;
				ViewBag.pageInfo = pageInfo;
				ViewBag.PageLink = PageHelper.getPageLink(totalCount, pageNum, limitCount);
			}
			catch (Exception e)
			{
				throw new Exception(e.Message);
			}

			return PartialView("~/VIews/Command/CommandList.cshtml");
		}

		public ActionResult Write()
		{
			try
			{
				CCommand command = new CCommand();
				if (Request["idx"] != null && int.Parse(Request["idx"]) > 0)
				{
					DaoCommand daoCommand = new DaoCommand();
					command = daoCommand.getCommandOne(int.Parse(Request["idx"]));

					//ViewBag.status = new DaoCode().getCodeList("status", 0, null, 0);
				}

				ViewBag.command = command;
			}
			catch (Exception e)
			{
				
				throw new Exception(e.Message);
			}
			return View("~/VIews/Command/CommandWrite.cshtml");
		}

		public ActionResult View()
		{
			try
			{
				if (Request["idx"] != null && int.Parse(Request["idx"]) > 0)
				{
					DaoCommand daoCommand = new DaoCommand();
					CCommand command = daoCommand.getCommandOne(int.Parse(Request["idx"]));
					ViewBag.command = command;
					if ( command.ord_emp_no.Equals( Session["emp_no"] ) )
					{
						ViewBag.IsAuth = true;
					}
					else
					{
						ViewBag.IsAuth = false;
					}

					ViewBag.status = new DaoCode().getCodeList("status", 0, null, 0);
				}
			}
			catch (Exception e)
			{

				throw new Exception(e.Message);
			}
			return View("~/VIews/Command/CommandView.cshtml");
		}

		[HttpPost]
		[ValidateInput(false)]
		public JObject Save()
		{
			JObject jsonObj = new JObject();

			try
			{
				DaoCommand daoCommand = new DaoCommand();
				CCommand command = new CCommand();
				command.subject = Request["subject"];
				command.ord_emp_no = Session["emp_no"].ToString();
				command.ord_emp_name = Request["ord_emp_no"];
				command.ord_type = Request["tree_value"];
				command.content = Request["content"];
				command.reg_ip = UtilityController.getUserIP(Request);

				if (Request["idx"] != null && Request["idx"].ToString() != "")
				{
					command.idx = int.Parse(Request["idx"]);
					command.reg_date = DateTime.Now;
					command.mod_date = DateTime.Now.Date;
					
				}
				else
				{
					command.mod_date = DateTime.Now;
				}
				daoCommand.setCommand(command);
				jsonObj.Add("RESULT", "OK");
			}
			catch (Exception e)
			{
				jsonObj.Add("RESULT", "FAIL");
				jsonObj.Add("MSG", e.Message);
				UtilityController.WriteLog(e.Message);
				//throw new Exception(e.Message);
			}

			return jsonObj;
		}

		[HttpPost]
		public JObject Delete()
		{
			JObject json = new JObject();
			try
			{
				int idx = int.Parse( Request["idx"].ToString() );
				new DaoCommand().deleteCommand(idx);
				json.Add("RESULT", "OK");
			}
			catch (Exception e)
			{
				json.Add("RESULT", "FAIL");
				json.Add("MSG", e.Message);
				//throw;
			}
			return json;
		}

    }
}

Groupware.WAS/Controllers/Partial/EditorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Groupware.Base.Controllers.Partial
{
    public class EditorController : Controller
    {
        //
        // GET: /Editor/

        public ActionResult Index(string content)
        {
			ViewBag.contents = content;
			return PartialView("~/Views/PartialView/ckeditor.cshtml", content);
        }

    }
}

Groupware.WAS/Controllers/Utilities/CodeController.cs
using DAO;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Groupware.Base.Controllers.Utilities
{
    public class CodeController : Controller
    {
		public ActionResult Index()
		{
			return View();
		}

		public ActionResult StatusList(string tree_type, int tree_level, string tree_value)
		{
			IList<CCode> listCode = new List<CCode>();
			try
			{
				DaoCode daoTree = new DaoCode();
				listCode = daoTree.getCodeList(tree_type, 0, null, tree_level);
				ViewBag.listCode = listCode;
				ViewBag.tree_value = (tree_value == null || tree_value == "") ? "" : tree_value;
			}
			catch (Exception e)
			{
				UtilityController.WriteLog(e.Message);
				throw new Exception(e.Message);
			}

			return PartialView("~/Views/PartialView/StatusView.cshtml", listCode);
		}

		public ActionResult CodePreview(string tree_type)
		{
			IList<CCode> listCode = new List<CCode>();
			try
			{
				if (tree_type == null || tree_type == "")
				{
					tree_type = "company";
				}

				DaoCode daoCode = new DaoCode();
				listCode = daoCode.getCodeList(tree_type, 0, null, 0);
				ViewBag.listCode = listCode;
				ViewBag.listCodeType = daoCode.getCodeTypeList();
			}
			catch (Exception e)
			{
				throw new Exception(e.Message);
			}

			return PartialView("~/Views/Code/CodePreview.cshtml", listCode);
		}

		public JsonResult getCodeOne(int tree_code)
		{
			CCode code = new CCode();
			JsonResult json = new JsonResult();

			HttpContext.GetGlobalResourceObject("c", "s");

			try
			{
				DaoCode daoTree = new DaoCode();

				code = daoTree.getCodeOne(tree_code);
				json.Data = code;
			}
			catch (Exception e)
			{
				throw new Exception(e.Message);
			}

			return json;
		}

		[HttpPost]
		public JObject setCodeOne(FormCollection form)
		{
			//Request.Form["frm"][];
			JObject jobj = new JObject();
			try
			{
				CCode code = new CCode();
				code.tree_code = form["tree_code"];
				code.tree_type = form["tree_type"];
				code.tree_level = form["tree_order"].Split('.').Length;
				code.tree_key = form["tree_key"];
				code.tree_value = form["tree_value"];
				code.tree_order = form["tree_order"];
				code.html_class = form["html_class"];

				new DaoCode().setCodeOne(code);
				jobj.Add("RESULT", "OK");

			}
			catch (Exception e)
			{
				jobj.Add("RESULT", "FAIL");
				jobj.Add("MSG", e.Message);
				//throw new Exception(e.Message);
			}
			return jobj;
		}

		[HttpPost]
		public JObject deleteCodeOne(FormCollection form)
		{
			//Request.Form["frm"][];
			JObject jobj = new JObject();
			try
			{
				new DaoCode().deleteCodeOne( int.Parse( form["tree_code"] ));

				jobj.Add("RESULT", "OK");

			}
			catch (Exception e)
			{
				jobj.Add("RESULT", "FAIL");
				jobj.Add("MSG", e.Message);
				//throw new Exception(e.Message);
			}
			return jobj;
		}



		public ActionResult CodeTree(string tree_type)
		{
			IList<CCode> listCode = new List<CCode>();
			try
			{
				if (tree_type == null || tree_type == "")
				{
					tree_type = "company";
				}

				DaoCode daoCode = new DaoCode();
				listCode = daoCode.getCodeList(tree_type, 0, null, 0);
				ViewBag.listCode = listCode;
				ViewBag.listCodeType = daoCode.getCodeTypeList();
			}
			catch (Exception e)
			{
				throw new Exception(e.Message);
			}

			return PartialView("~/Views/Code/CodeTree.cshtml", listCode);
		}

    }
}

Groupware.WAS/Views/Command/CommandList.cshtml
@{
	ViewBag.Title = "CommandList";
	var list_type = (Request["list_type"] == null) ? "all" : Request["list_type"];
}
<script src="/js/plugins/dataTables/jquery.dataTables.js"></script>
<script type="text/javascript">

	$(document).ready(function () {

		$('#btn-@list_type').addClass("active");
	});

	var goMyList = function (list_type) {
		showLoading();
		location.href = "/command/?list_type=" + list_type;
	}

</script>


<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                @ViewBag.PanelTitle
            </div>
            <!-- /.panel-heading -->

			<!-- /.panel-body -->
			<div class="panel-body">
				<!-- Nav tabs -->
				<ul class="nav nav-pills">
					<button class="btn btn-outline btn-default" id="btn-all" type="button" onclick="javascript:goMyList('all');">ALL</button>
					<button class="btn btn-outline btn-success" id="btn-receive" type="button" onclick="javascript:goMyList('receive');">Receive</button>
					<button class="btn btn-outline btn-info" id="btn-send" type="button" onclick="javascript:goMyList('send');">Send</button>
				</ul>
			</div>

            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th class="center">no</th>
                                <th>subject</th>
                                <th class="center">writer</th>
                                <th class="center">views</th>
                                <th class="center">date</th>
                            </tr>
                        </thead>
                        <tbody>
							@{
							var i =0;
							foreach (var item in ViewBag.listCommand)
							{
								var no = @ViewBag.pageInfo.TotalItems - ((ViewBag.pageInfo.CurrentPage -1) * ViewBag.pageInfo.ItemsPerPage) - i;
                            <tr class="odd gradeX">
                                <td class="center" style="width:5%;">@no</td>
                                <td><button class="btn btn-xs btn-@item.html_class" name="btn-list">@item.tree_key</button> <a href="javascript:goView('/Command/View', @item.idx);">@item.subject</a></td>
                                <td class="center" style="width:10%;">@item.ord_emp_name</td>
                                <td class="center" style="width:5%;">@item.hit</td>
                                <td class="center" style="width:15%;">@item.mod_date</td>
                            </tr>
								i++;
							}
							}
                        </tbody>
                    </table>

					@ViewBag.PageLink

					<div style="text-align: right;">
						<button class="btn btn-primary" id="btn-write" type="button" onclick="javascript:goPage('/Command/Write');">Write</button>
					</div>

                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

Groupware.WAS/Views/Command/CommandView.cshtml
@{
    ViewBag.Title = "업무 상세내용";
	var command = ViewBag.command;
	
}


<script type="text/javascript">

	$(document).ready(function () {
		$('#btn-update').click(function () {
			goView("/Command/Write", getParameter("idx"));
		});

		$('#btn-delete').click(function () {

			showDelete("DELETE", "삭제하시겠습니까?", "deleteCommandOne();");
		});

	});

	var deleteCommandOne = function () {
		getProcess("/Command/Delete", { idx : getParameter("idx") }, "goList('Command');" );
	}

</script>


<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                @ViewBag.PanelTitle
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">

				<div class="panel panel-@ViewBag.command.html_class">
					<div class="panel-body">
						<button class="btn btn-@ViewBag.command.html_class ">@ViewBag.command.tree_key</button>
					</div>
					<div class="panel-heading">
						@ViewBag.command.subject - @ViewBag.command.ord_emp_name
					</div>
					<div class="panel-body">
						@Html.Raw( ViewBag.command.content )
					</div>
					<div class="panel-footer">
						(@ViewBag.command.reg_date / @ViewBag.command.mod_date)
					</div>
				</div>

				<div style="text-align: right;">
					@if (ViewBag.IsAuth == true)
					{
						<button class="btn btn-primary" id="btn-update" type="button">UPDATE</button>
						<button class="btn btn-danger" id="btn-delete" type="button">DELETE</button>
					}
					<button class="btn btn-default" id="btn-cancel" type="button" onclick="javascript:goList('Command');">Back</button>
				</div>

				

			</div>
		</div>
	</div>
</div>

@{
	Html.RenderAction("List", "Command");
}

Groupware.WAS/Views/Command/CommandWrite.cshtml
@{
    ViewBag.Title = "업무지시";
	
}


<script type="text/javascript">

	$(document).ready(function () {

	});

	var regist = function () {
		syncContent();

		if ($('#subject').val() == "") {
			showAlert("Validate", "Subject is Empty", false);
			return false;
		}
		if ($('#name').val() == "") {
			showAlert("Validate", "Writer's Name is Empty", false);
			return false;
		}

		doProcess("/Command/Save", "frm", "saveCommand(data)");
	}

	var saveCommand = function (data) {
		goPage("/Command/");
	}

</script>


<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                @ViewBag.PanelTitle
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">


				<form id="frm" name="frm" method="post">
				<input type="hidden" id="idx" name="idx" value="@ViewBag.command.idx" />

				<div class="form-group">
					<label>command type</label>
					@{
						Html.RenderAction("StatusList", "Code", new RouteValueDictionary { { "tree_type", "status" }, { "tree_level", 2 }, { "tree_value", @ViewBag.command.ord_type } });
					}
				</div>
				<div class="form-group">
					<label>subject</label>
					<input class="form-control" placeholder="Enter Subject" id="subject" name="subject"  value="@ViewBag.command.subject">
				</div>
				<div class="form-group">
					<label>writer</label>
					<input class="form-control" placeholder="Enter Writer's Name" id="ord_emp_no" name="ord_emp_no" value="@Session["name"]"  value="@ViewBag.command.ord_emp_name">
				</div>
				<div class="form-group">
					<label>receives</label>
					<button class="btn btn-primary" id="btn-receives" type="button" onclick="javascript:showEmpSelector();">selecting</button>
					<input type="text" id="sel_emp_nos" name="sel_emp_nos" />
					<div id="sel_emp_no"></div>
				</div>
				<div class="form-group">
                    <label>Content</label>
					@{
						Html.RenderAction("Index", "Editor", new RouteValueDictionary { { "content", @ViewBag.command.content} });
					}
                    @*<textarea class="form-control" rows="15" id="content" name="content"></textarea>*@
                </div>

				<div style="text-align: right;">
					<button class="btn btn-primary" id="btn-save" type="button" onclick="javascript:regist();">Save</button>
					<button class="btn btn-default" id="btn-cancel" type="button" onclick="javascript:goBack();">Cancel</button>
				</div>

				</form>


			</div>
		</div>
	</div>
</div>

Groupware.WAS/Views/Command/Index.cshtml
@{
	ViewBag.Title = "업무목록";
}
<div class="row">
    <div class="col-lg-12">
        
		@{
			Html.RenderAction("List", "Command");
		}

    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->